# Generated by Django 3.0.7 on 2020-06-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticFlatPage',
        ),
    ]
