# Generated by Django 3.0.6 on 2020-06-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200610_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='subCategory',
            new_name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='describe',
        ),
    ]
